### ISSUE TITLE
Todo Liste

### ISSUE THREAD

**Issue by asteding** [JGDoerrer/selection_generator#1]
# Arbeitspunkte Meilenstein Implementierung - Deadline 31.01.2024

- [ ] Threading (Untere/Obere Schranke)
  - [ ] Baumaufteilung
  - [ ] Synchronisierung
  - [ ] Threadpool
- [ ] Analytische Lösung
- [ ] Mikrooptimierungen des bestehenden Codes
  - [ ] Allokationen
  - [ ] Mehrfachberechnung von Werten...
  - [ ] Das übliche halt 
- [ ] Heuristiken
  - [ ] Normalform 
  - [ ] Nauty 
  - [ ] Hash
  - [ ] Mixform finden, eigene Implementierung verwenden um dann Nauty aufzurufen
- [ ] Backward-Search
  - [ ]  potentielle Lösungen der Forward-Search für Backward-Search verwenden
- [ ] Code zusammenführen, C++ und Rust nicht mehr in Branches führen
